# Generated by Django 5.2.5 on 2025-09-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='description',
            field=models.TextField(help_text='Maximum 50 characters required'),
        ),
    ]
