# Generated by Django 5.2 on 2025-09-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0002_alter_disaster_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='description',
            field=models.TextField(help_text='Minimum 50 characters required'),
        ),
    ]
