# Generated by Django 5.2.5 on 2025-09-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0003_alter_disaster_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='description',
            field=models.TextField(help_text='Maximum 50 characters required', max_length=50),
        ),
    ]
