# Generated by Django 5.2.5 on 2025-10-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0004_alter_disaster_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
