# Generated by Django 5.2 on 2025-09-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizenprofile',
            old_name='frequent_district',
            new_name='area_sector',
        ),
        migrations.RenameField(
            model_name='citizenprofile',
            old_name='frequent_post_office',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='citizenprofile',
            old_name='frequent_upazila',
            new_name='emergency_contact_name',
        ),
        migrations.RenameField(
            model_name='citizenprofile',
            old_name='emergency_contact',
            new_name='emergency_contact_phone',
        ),
        migrations.RenameField(
            model_name='citizenprofile',
            old_name='frequent_post_code',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='frequent_address_details',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='frequent_division',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='permanent_address_details',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='permanent_district',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='permanent_division',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='permanent_post_code',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='permanent_post_office',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='permanent_upazila',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='present_address_details',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='present_district',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='present_division',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='present_post_code',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='present_post_office',
        ),
        migrations.RemoveField(
            model_name='citizenprofile',
            name='present_upazila',
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='available_to_donate',
            field=models.CharField(blank=True, choices=[('', 'Select Option'), ('yes', 'Yes'), ('no', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='house_road_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='landmarks',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='last_blood_donation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
