# Generated by Django 5.2 on 2025-09-11 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_frequent_district_citizenprofile_area_sector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('hospital', 'Hospital'), ('ambulance', 'Ambulance Service'), ('fire_station', 'Fire Station'), ('police_station', 'Police Station'), ('military_camp', 'Military Camp'), ('forces_hq', 'Forces Headquarters'), ('emergency_response', 'Emergency Response Unit'), ('others', 'Others')], max_length=20)),
                ('service_type_other', models.CharField(blank=True, help_text="Specify if 'Others' is selected", max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('registration_number', models.CharField(blank=True, help_text='Official registration/license number', max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=300)),
                ('area_sector', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('specialized_services', models.TextField(blank=True, help_text='List specialized services offered')),
                ('equipment_available', models.TextField(blank=True, help_text='List major equipment/resources')),
                ('staff_count', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('average_response_time', models.PositiveIntegerField(blank=True, help_text='Average response time in minutes', null=True)),
                ('primary_contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_person_designation', models.CharField(blank=True, max_length=100)),
                ('emergency_hotline', models.CharField(blank=True, max_length=15)),
                ('emergency_email', models.EmailField(blank=True, max_length=254)),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=15)),
                ('current_capacity', models.PositiveIntegerField(blank=True, help_text='Current available capacity', null=True)),
                ('operating_hours', models.CharField(blank=True, default='24/7', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_providers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=50, unique=True)),
                ('response_time', models.PositiveIntegerField(help_text='Response time in minutes')),
                ('status', models.CharField(choices=[('received', 'Received'), ('dispatched', 'Dispatched'), ('on_scene', 'On Scene'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_responses', to='accounts.serviceproviderprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProviderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.serviceproviderprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('service_provider', 'user')},
            },
        ),
    ]
