# Generated by Django 5.2 on 2025-09-27 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_serviceproviderprofile_emergencyresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='emergency_donor',
            field=models.BooleanField(default=False, help_text='Available for emergency blood donation'),
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(help_text='Person making the request', max_length=100)),
                ('patient_name', models.CharField(help_text='Patient who needs blood', max_length=100)),
                ('blood_type_needed', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('location', models.CharField(help_text='Hospital/location where blood is needed', max_length=200)),
                ('contact_phone', models.CharField(max_length=15)),
                ('urgency', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('needed_by_date', models.DateField(help_text='When is the blood needed by')),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional information')),
                ('requester_city', models.CharField(blank=True, help_text='City for filtering purposes', max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('fulfilled', 'Fulfilled')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this request (if logged in)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blood_type_needed'], name='accounts_bl_blood_t_02cc94_idx'), models.Index(fields=['requester_city'], name='accounts_bl_request_6144f2_idx'), models.Index(fields=['status'], name='accounts_bl_status_80dff4_idx'), models.Index(fields=['urgency'], name='accounts_bl_urgency_de5c3a_idx')],
            },
        ),
    ]
