# Generated by Django 5.2 on 2025-09-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_citizenprofile_emergency_donor_bloodrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='bags_needed',
            field=models.PositiveIntegerField(default=1, help_text='Number of blood bags needed'),
        ),
    ]
